// A "Section" on a study guide is not a "Topic". A "Section" is an Example, Question, Answer, Video, or Explanation.
import React from "react";
import styled from "styled-components";
import { X, Sparkles } from "lucide-react";
import IconButton from "../IconButton";
import Button from "../Button";

const SectionHeader = ({
  sectionName,
  topic,
  editMode,
  setAutoGenerateSection,
  setTopicForAutoGenerate,
  setIsAutoGenerateDialogOpen,
  setTopicToDelete,
  setSectionToDelete,
  setIsDeleteSectionDialogOpen,
  toggleAnswer,
  collapsedAnswers
}) => {
  const lowercaseSectionName = sectionName.toLowerCase();
  return (
    <Container>
      <SectionHeaderTitle>{sectionName}:</SectionHeaderTitle>
      {editMode && sectionName !== "Answer" && (
        <ButtonContainer>
          <IconButton
            icon={<Sparkles size={20} />}
            onClick={() => {
              setAutoGenerateSection(lowercaseSectionName);
              setTopicForAutoGenerate(topic);
              setIsAutoGenerateDialogOpen(true);
            }}
            title={"Auto-generate" + sectionName}
          />
          <IconButton
            icon={<X size={20} />}
            onClick={() => {
              setTopicToDelete(topic);
              setSectionToDelete(lowercaseSectionName);
              setIsDeleteSectionDialogOpen(true);
            }}
            title={"Delete " + sectionName}
          />
        </ButtonContainer>
      )}
      {!editMode && sectionName === "Answer" && (
        <Button
          onClick={() => toggleAnswer(topic)}
          padding="8px"
          fontSize={({ theme }) => theme.fontSize.label}
          backgroundColor={({ theme }) => theme.primary70}
          hoverBackgroundColor={({ theme }) => theme.primary70}
          textColor={({ theme }) => theme.black}
          hoverTextColor={({ theme }) => theme.white}
        >
          {!collapsedAnswers[topic] ? "SHOW" : "HIDE"}
        </Button>
      )}
    </Container>
  );
};

export default SectionHeader;

const Container = styled.div`
  display: flex;
  width: 100%;
  align-items: center;
  justify-content: space-between;
`;

const SectionHeaderTitle = styled.p`
  font-weight: bold;
`;

const ButtonContainer = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
`;
