// A "Section" on a study guide is not a "Topic". A "Section" is an Example, Question, Answer, Video, or Explanation.
import React from "react";
import styled from "styled-components";
import { X, Sparkles } from "lucide-react";
import IconButton from "../IconButton";
import Button from "../Button";
import AutoResizeTextArea from "./AutoResizeTextArea";

const TopicSection = ({
  sectionName,
  topic,
  editMode,
  setAutoGenerateSection,
  setTopicForAutoGenerate,
  setIsAutoGenerateDialogOpen,
  setTopicToDelete,
  setSectionToDelete,
  setIsDeleteSectionDialogOpen,
  toggleAnswer,
  collapsedAnswers,
  updateStudyGuideObject,
  sectionText,
}) => {
  const lowercaseSectionName = sectionName.toLowerCase();
  return (
    <SectionContainer>
      <HeaderContainer>
        <SectionHeaderTitle>{sectionName}:</SectionHeaderTitle>
        {editMode && sectionName !== "Answer" && (
          <ButtonContainer>
            <IconButton
              icon={<Sparkles size={20} />}
              onClick={() => {
                setAutoGenerateSection(lowercaseSectionName);
                setTopicForAutoGenerate(topic);
                setIsAutoGenerateDialogOpen(true);
              }}
              title={"Auto-generate" + sectionName}
            />
            <IconButton
              icon={<X size={20} />}
              onClick={() => {
                setTopicToDelete(topic);
                setSectionToDelete(lowercaseSectionName);
                setIsDeleteSectionDialogOpen(true);
              }}
              title={"Delete " + sectionName}
            />
          </ButtonContainer>
        )}
        {!editMode && sectionName === "Answer" && (
          <Button
            onClick={() => toggleAnswer(topic)}
            padding="8px"
            fontSize={({ theme }) => theme.fontSize.label}
            backgroundColor={({ theme }) => theme.primary70}
            hoverBackgroundColor={({ theme }) => theme.primary70}
            textColor={({ theme }) => theme.black}
            hoverTextColor={({ theme }) => theme.white}
          >
            {!collapsedAnswers[topic] ? "SHOW" : "HIDE"}
          </Button>
        )}
      </HeaderContainer>
      {typeof sectionText === "string" && sectionName !== "Answer" && (
        <AutoResizeTextArea
          key={editMode} // Trigger re-render when edit mode changes
          onChange={(text) => {
            updateStudyGuideObject(topic, lowercaseSectionName, text);
          }}
          value={sectionText}
          editMode={editMode}
        />
      )}
      {typeof sectionText === "string" &&
        sectionName === "Answer" &&
        (editMode ? (
          // In edit mode, always show the text area
          <AutoResizeTextArea
            key={editMode} // Trigger re-render when edit mode changes
            onChange={(text) => {
              updateStudyGuideObject(topic, lowercaseSectionName, text);
            }}
            value={sectionText}
            editMode={editMode}
          />
        ) : (
          // In view mode, show the text area only if the answer is not collapsed
          collapsedAnswers[topic] && (
            <AutoResizeTextArea
              key={editMode} // Trigger re-render when edit mode changes
              onChange={(text) => {
                updateStudyGuideObject(topic, lowercaseSectionName, text);
              }}
              value={sectionText}
              editMode={editMode}
            />
          )
        ))}
    </SectionContainer>
  );
};

export default TopicSection;

const SectionContainer = styled.div`
  display: flex;
  font-size: ${({ theme }) => theme.fontSize.label};
  text-align: left;
  flex-direction: column;
  border-radius: 12px;
  padding: 16px;
  width: 100%;
`;

const HeaderContainer = styled.div`
  display: flex;
  width: 100%;
  align-items: center;
  justify-content: space-between;
`;

const SectionHeaderTitle = styled.p`
  font-weight: bold;
`;

const ButtonContainer = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
`;
